version: '3.9'

services:
    website:
        image: docker.io/library/fintech_conference_2023-website:latest
        container_name: fintech_conference_2025_website
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: fintech_conference_2025_website
        working_dir: /var/www
        ports:
            - "9025:9000"
        volumes:
            - ./:/var/www
            - ./php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - fintech_highlight_app-network

networks:
  fintech_highlight_app-network:
    driver: bridge
    external: true